import React, { useState } from "react";

// This helper function is generated by `dfx generate`
import { certify_v1_backend } from "../../declarations/certify_v1_backend";

// I think this is pretty self explanatory
const App = () => {
  const [message, setMessage] = useState("");
  const [greeting, setGreeting] = useState<string>();

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setMessage(e.target.value);
  };

  const doGreet = async () => {
    // God I lovvvvveeee this helper functions. It even handle result types
    const greeting = await certify_v1_backend.greet(message);
    setGreeting(greeting);
  };

  return (
    <div className="w-screen h-screen flex justify-center items-center">
      <div className="rounded-xl p-5 text-center max-w-[50%] border border-black">
        <p className="my-4">Welcome to certify</p>
        <p className="my-4">
          This is the sample frontend container.
          <br />
          This just sends a greeting to backend canister and shows the response
        </p>
        <input
          className="my-5 border w-3/4 p-3 border-black rounded-lg text-center"
          placeholder="Enter your greeting"
          type="text"
          onChange={handleInputChange}
        />
        <br />
        <button
          className="p-3 rounded-lg border border-black"
          onClick={doGreet}
        >
          Send Greeting
        </button>
        {greeting && (
          <>
            <p className="text-xl my-5">Greeting</p>
            <p>{greeting}</p>
          </>
        )}
      </div>
    </div>
  );
};

export default App;
